### ISSUE TITLE
DSDT patches

### ISSUE THREAD

**Issue by sukkritsharmaofficial** [alex-spataru/HP-Spectre-4101dx-Hackintosh#2]
Did you patch your own DSDT's or used the prebuilt ones on the dortania guide ?? 

If you are using the prebuilt ones please tell me how good is the performance and if I should go for them instead of patching my own since we all know its a huge pain XD

**Comment by alex-spataru** [comment]
Hi, I am using both the prebuilt DSDT patches from the Dortania guide and some custom patches to get battery & trackpad to work. The Dortania DSDT files work pretty well, I don't have any issues with performance. 

For more information regarding the DSDT patches that I aplied, check the [ACPI](https://github.com/alex-spataru/HP-Spectre-4101dx-Hackintosh/tree/master/ACPI) folder, I just uploaded it. Please let me know if they work for you!
