### ISSUE TITLE
HP Spectre x360 Convertible 13-ae0xx can't follow your OC startup MAC 10.15.6

### ISSUE THREAD

**Issue by jimchun** [alex-spataru/HP-Spectre-4101dx-Hackintosh#4]
Model: HP Spectre x360 Convertible 13-ae0xx
OS:       Windows 10 64-bit (DirectX 12)
CPU:    Intel Core i7-8550U @ 1.80GHz 4core
board: HP 83B9 (7th/8th Generation Intel Processor Family I/O-9D4E Notebook Chipset)
RAM:   16 GB (SK Hynix LPDDR3 2133MHz)
HD:      HS-SSD-C2000Pro 2048GB (2048 GB / solid state drive)
Graphics: Intel UHD Graphics 620 (128 MB / HP)
Display: LG LGD0588 (13.3 inches)
Sound Card: Realtek @ Intel High Definition Audio Controller
Network card: Intel Dual Band Wireless-AC 8265

the attached is my pc's ACPI info

[ACPI_origin.zip](https://github.com/alex-spataru/HP-Spectre-4101dx-Hackintosh/files/4998845/ACPI_origin.zip)

**Comment by alex-spataru** [comment]
My current OpenCore configuration is for Broadwell CPUs. [Your CPU](https://ark.intel.com/content/www/us/en/ark/products/122589/intel-core-i7-8550u-processor-8m-cache-up-to-4-00-ghz.html) seems to be a Kaby Lake CPU, which explains why my OC config does not work with your laptop. To get OpenCore to work with your configuration, you can follow [Dortania's guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html) for Kaby Lake CPUs.

**Comment by alex-spataru** [comment]
**Edit:** follow [this](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html) guide. The previous link is for desktop computers.

**Comment by jimchun** [comment]
Thank U ! I will try the guide, and will update the detail late.

**Comment by alex-spataru** [comment]
@jimchun Any updates on your hackintosh laptop?
