### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by cassova** [alex-spataru/HP-Spectre-4101dx-Hackintosh#5]
First, thanks for this!  It works great.  I have the same laptop (HP Spectre 4101dx) and for the most part had no issues with this except for the audio.  It doesn't seem to be working at all.  I know you say you got audio via VoodooHDA but are there some extra steps I need to follow to get this to work?  (I installed macOS Catalina 10.15.6)

**Comment by alex-spataru** [comment]
Hi, sorry for the late reply.

I had the same issue when rebooting into different operating systems. To fix this, you need to force your computer to shutdown while running macOS (just press the power button for some seconds). After one or two trials, the audio should begin working.

Note: I stopped using VoodooHDA, instead, the updated configuration uses AppleALC with layout-id 11. Both audio output speaker/headphones and microphone work with this layout.
